name: GreenFilter
version: '1.0'
main: net.multylands.greenfilter.GreenFilter
authors: [ GreenedDev ]
description: Filter plugin created for Multylands
api-version: 1.20
commands:
  chat:
    aliases: [greenfilter, filtergreen]